# Makefile for AW_View
# 
# @author Eduardo Calderini Jr <ecalderini@ydeasolutions.com.br>


ifndef ($(PREFIX))
	PREFIX=/usr/local
endif
INCLUDE_PREFIX=$(PREFIX)/include/kowview
LIB_PREFIX=$(PREFIX)/lib
GPR_PREFIX=$(LIB_PREFIX)/gnat



################
# Main targets #
################
all: libs

libs:
	gnatmake -P kowview.gpr

clean: 
	gnatclean -P kowview.gpr
	@echo "All clean"

docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms than Linux"

install:
	@cat INSTALL




gprfile:
	@echo "Preparing GPR file.."
	@echo version:=\"$(VERSION)\" > gpr/kowview.def
	@echo prefix:=\"$(PREFIX)\" >> gpr/kowview.def
	@gnatprep gpr/kowview.gpr.in gpr/kowview.gpr gpr/kowview.def

gprclean:
	@rm -f gpr/*gpr
	@rm -f gpr/*.def


install: gprfile
	@echo "Installing files"
	install -d $(INCLUDE_PREFIX)
	install -d $(LIB_PREFIX)
	install -d $(GPR_PREFIX)
	install src/* -t $(INCLUDE_PREFIX)
	install lib/* -t $(LIB_PREFIX)
	install gpr/*.gpr -t $(GPR_PREFIX)
	make gprclean
