


-- This file has ben automatically generated by the kvdriver tool
-- Please do no edit!


@@TABLE@@
with @_modules_gprs_@;
@@END_TABLE@@


project @_project_name_@ is

	Version := @_version_string_@;
	--

end @_project_name_@;
